version: '3.8'

services:
  redis:
    image: redis:latest
    networks:
      - backup-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.web
    image: docker.codelinq.com/tiktok-web:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    environment:
      - REDIS_HOST=redis
      - WORKERS=4
      - TIMEOUT=120
    networks:
      - backup-network
    depends_on:
      - redis

  url_discovery:
    # build:
    #   context: .
    #   dockerfile: services/discovery.Dockerfile
    image: docker.codelinq.com/tiktok-url-discovery:latest
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    environment:
      - REDIS_HOST=redis
    command: python services/url_discovery.py
    networks:
      - backup-network
    depends_on:
      - redis

  # metadata:
  #   build:
  #     context: .
  #     dockerfile: services/metadata.Dockerfile
  #     image: docker.codelinq.com/tiktok-metadata:latest
  #   volumes:
  #     - .:/app
  #     - ./downloads:/app/downloads
  #   environment:
  #     - REDIS_HOST=redis
  #   command: python services/metadata_service.py
  #   networks:
  #     - backup-network
  #   depends_on:
  #     - redis

  # downloader:
  #   build:
  #     context: .
  #     dockerfile: services/downloader.Dockerfile
  #     image: docker.codelinq.com/:latest
  #   volumes:
  #     - .:/app
  #     - ./downloads:/app/downloads
  #   environment:
  #     - REDIS_HOST=redis
  #   command: python services/video_downloader.py
  #   networks:
  #     - backup-network
  #   depends_on:
  #     - redis

  redis-backup:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.backup
    image: docker.codelinq.com/tiktok-redis-backup:latest
    volumes:
      - ./backups:/app/backups
    environment:
      - REDIS_HOST=redis
    networks:
      - backup-network
    depends_on:
      - redis
    stdin_open: true
    tty: true

networks:
  backup-network:
    driver: bridge

volumes:
  redis-data:
