version: '3.8'

services:
  redis:
    image: redis:latest
    networks:
      - backup-network
    ports:
      - "6379:6379"

  redis-backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    volumes:
      - ./backups:/app/backups
    environment:
      - REDIS_HOST=redis
    networks:
      - backup-network
    depends_on:
      - redis
    stdin_open: true
    tty: true

networks:
  backup-network:
    driver: bridge
